### ISSUE TITLE
打开程序时：加载错误

### ISSUE THREAD

**Issue by xp990303** [DeleteIT/Tian-s-World#1]
使用环境：mocos 卡特琳娜 matlab2019b
<img width="406" alt="截屏2020-06-12 上午3 16 26" src="https://user-images.githubusercontent.com/49979425/84429683-2b7f8400-ac5b-11ea-81fd-2ab281aeabb9.png">

**Comment by YuetianW** [comment]
您好，谢谢您的反馈。
我刚查看了一下，可能是代码的格式不太对。
我重新上传了一份源代码。
请您打开app1.mlapp试试。
如果还存在问题，欢迎您与我联系
